services:
  - type: web
    name: the-ev-network
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
